Group3_Project/Group3_Project_08_09_2020/FA.Project/Fa.Present/Areas/Admin/Controllers/Requests3Controller.cs
using FA.Core.Services;
using FA.Project.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Fa.Present.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class Requests3Controller : Controller
    {
        private readonly TMSContext _context;
        private readonly IRequestServices _requestServices;
        public Requests3Controller(TMSContext context, IRequestServices requestServices)
        {
            _context = context;
            _requestServices = requestServices;
        }
        public async Task<IActionResult> Index()
        {
            var tMSContext = _context.Requests.Include(r => r.Trainee).Include(x => x.ClassAdmin);
            return View(await tMSContext.ToListAsync());
        }

        // GET: Admin/Requests3/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var request = await _requestServices.GetByIdAsync((int)id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Admin/Requests3/Create
        public IActionResult Create()
        {
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "Account");
            ViewData["ClassAdminId"] = new SelectList(_context.ClassAdmins, "ClassAdminId", "Account");
            return View();
        }

        // POST: Admin/Requests3/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RequestId,Requesttype,Reason,StartDate,EndDate,ComimmingTime,LeavingTime,ExpectedApproval,ApprovedTime,Status,AuditTrail,isDelete,TraineeId,ApproverId")] Request request)
        {
            if (ModelState.IsValid)
            {
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "Account", request.TraineeId);
            ViewData["ClassAdminId"] = new SelectList(_context.ClassAdmins, "ClassAdminId", "Account", request.ApproverId);
            return View(request);
        }

        // GET: Admin/Requests3/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var request = await _context.Requests.FindAsync(id);
            // var request = await _context.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "Account", request.TraineeId);
            ViewData["ClassAdminId"] = new SelectList(_context.ClassAdmins, "ClassAdminId", "Account", request.ApproverId);
            return View(request);
        }

        // POST: Admin/Requests3/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RequestId,Requesttype,Reason,StartDate,EndDate,ComimmingTime,LeavingTime,ExpectedApproval,ApprovedTime,Status,AuditTrail,isDelete,TraineeId,ApproverId")] Request request)
        {
            if (id != request.RequestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _requestServices.UpdateAsync(request);
                    //_context.Update(request);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.RequestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TraineeId"] = new SelectList(_context.Trainees, "TraineeId", "Account", request.TraineeId);
            ViewData["ClassAdminId"] = new SelectList(_context.ClassAdmins, "ClassAdminId", "Account", request.ApproverId);
            return View(request);
        }

        // GET: Admin/Requests3/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .Include(r => r.Trainee)
                .FirstOrDefaultAsync(m => m.RequestId == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Admin/Requests3/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await _context.Requests.FindAsync(id);
            _context.Requests.Remove(request);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
            return _context.Requests.Any(e => e.RequestId == id);
        }
    }
}

Group3_Project/Group3_Project_08_09_2020/FA.Project/Fa.Present/Areas/Admin/Controllers/Trainees1Controller.cs
using FA.Core.Services;
using FA.Project.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Fa.Present.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class Trainees1Controller : Controller
    {
        private readonly TMSContext _context;
        private readonly ITraineeServices _traineeServices;
        public Trainees1Controller(TMSContext context, ITraineeServices traineeServices)
        {
            _context = context;
            _traineeServices = traineeServices;
        }
        //// GET: Admin/Trainees
        //public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        //{
        //    ViewData["CurrentPageSize"] = pageSize;
        //    ViewData["CurrentSort"] = sortOrder;
        //    ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    if (searchString != null)
        //    {
        //        pageIndex = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }

        //    ViewData["CurrentFilter"] = searchString;

        //    Expression<Func<Trainee, bool>> filter = null;

        //    if (!string.IsNullOrEmpty(searchString))
        //    {
        //        filter = c => c.Account.Contains(searchString);
        //    }

        //    Func<IQueryable<Trainee>, IOrderedQueryable<Trainee>> orderBy = null;

        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            orderBy = q => q.OrderByDescending(c => c.Account);
        //            break;
        //        default:
        //            orderBy = q => q.OrderBy(c => c.Account);
        //            break;
        //    }

        //    var trainees = await _traineeServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

        //    return View(trainees);


        //    //var tMSContext = _context.Trainees.Include(t => t.ClassBatch);
        //    //return View(await tMSContext.ToListAsync());
        //}


        // GET: Admin/Trainees1
        public async Task<IActionResult> Index()
        {
            var tMSContext = _context.Trainees.Include(t => t.ClassBatch);
            return View(await tMSContext.ToListAsync());
        }

        // GET: Admin/Trainees1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var trainee = await _traineeServices.GetByIdAsync((int)id);
            //var trainee = await _context.Trainees
            //    .Include(t => t.ClassBatch)
            //    .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // GET: Admin/Trainees1/Create
        public IActionResult Create()
        {
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail");
            return View();
        }

        // POST: Admin/Trainees1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TraineeId,FullName,DateOfBirth,Gender,PhoneNumber,FamilyPhoneNumber,Email,ExternalEmail,Account,OnboardDate,Status,Remarks,University,Faculty,Skill,ForeignLanguage,Level,CV,AllocationStatus,AuditTrail,isDelete,ClassBatchId")] Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // GET: Admin/Trainees1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var trainee = await _context.Trainees.FindAsync(id);
            //var trainee = await _context.Trainees.FindAsync(id);
            if (trainee == null)
            {
                return NotFound();
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // POST: Admin/Trainees1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TraineeId,FullName,DateOfBirth,Gender,PhoneNumber,FamilyPhoneNumber,Email,ExternalEmail,Account,OnboardDate,Status,Remarks,University,Faculty,Skill,ForeignLanguage,Level,CV,AllocationStatus,AuditTrail,isDelete,ClassBatchId")] Trainee trainee)
        {
            if (id != trainee.TraineeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _traineeServices.UpdateAsync(trainee);
                    //_context.Update(trainee);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TraineeExists(trainee.TraineeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // GET: Admin/Trainees1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .Include(t => t.ClassBatch)
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // POST: Admin/Trainees1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainee = await _context.Trainees.FindAsync(id);
            _context.Trainees.Remove(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.TraineeId == id);
        }
    }
}

Group3_Project/Group3_Project_08_09_2020/FA.Project/Fa.Present/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fa.Present</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <style>
        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: #818181;
                display: block;
                transition: 0.3s;
            }

                .sidenav a:hover {
                    color: #f1f1f1;
                }

            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

        body {
            /* Margin bottom by footer height */
            background-image: url(./a1.jpg);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div>
                <a class=" navbar-brand" id="BigText" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/css/FPTlogo.png" alt="" style="height: 30px; width: auto">
                    Time Manage System
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <span style="font-size:30px;cursor:pointer" onclick="openNav()">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-menu-app-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 1.5A1.5 1.5 0 0 1 1.5 0h2A1.5 1.5 0 0 1 5 1.5v2A1.5 1.5 0 0 1 3.5 5h-2A1.5 1.5 0 0 1 0 3.5v-2zM14 7H2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1zM2 6a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H2z" />
                    <path fill-rule="evenodd" d="M15 11H1v-1h14v1zM2 12.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5z" />
                </svg>
            </span>
        </nav>
    </header>
    
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        <div>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Request
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-area="Admin" asp-controller="Requests3" asp-action="Create" style="color:black">Create request</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-area="Admin" asp-controller="Requests3" asp-action="Index" style="color:black">All Request</a>
            </div>
        </div>
        <div>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Trainee
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-area="Admin" asp-controller="Trainees1" asp-action="Create" style="color:black">Create Trainee</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-area="Admin" asp-controller="Trainees1" asp-action="Index" style="color:black">All Trainee</a>
            </div>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Fa.Present - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>